#!/usr/bin/env bash

alias my_ip="ip address | grep -o \"inet 192.*/\" | awk '{ print \$2 }' | tr / ' ' | xargs"
alias python="python3"
alias pbcopy="xsel --input --clipboard"
alias pbpaste="xsel --output --clipboard"
alias cat="batcat"

alias ls="ls -la"

alias czsh="batcat $DOTFILES/zsh/.zshrc"
alias caliases="batcat $DOTFILES/zsh/.zsh-config/aliases"
alias cfunctions="batcat $DOTFILES/zsh/.zsh-config/functions"
alias cpath="batcat $DOTFILES/zsh/.zsh-config/path"
alias edot="code $DOTFILES"
alias dotFileInstall="$DOTFILES/install_ubuntu"
alias f5="dotFileInstall && source ~/.zshrc"

