#!/usr/bin/env bash

export GOPATH=$HOME/go
export DOTFILES=$HOME/.dotfiles
export PR="$HOME/projects"

addToPath /usr/local/go/bin
addToPath $GOPATH/bin
addToPathFront $HOME/.local/bin
addToPathFront $HOME/.local/scripts

#add node
