#!/usr/bin/env bash

alias dotFileInstall="$DOTFILES/install"
alias my_ip="ip address | grep -o \"inet 192.*/\" | awk '{ print \$2 }' | tr / ' ' | xargs"
alias python="python3"

alias ls="ls -la"
#  alias ls="eza --icons --group-directories-first"
#  alias ll="eza --icons --group-directories-first -l"

alias pbcopy="xsel --input --clipboard"
alias pbpaste="xsel --output --clipboard"

alias f5="exec zsh"
