#!/usr/bin/env bash

alias my_ip="ip address | grep -o \"inet 192.*/\" | awk '{ print \$2 }' | tr / ' ' | xargs"
alias python="python3"
alias pbcopy="xsel --input --clipboard"
alias pbpaste="xsel --output --clipboard"
alias cat="batcat"


alias ls="ls -la"

alias czsh="batcat $DOTFILES/zsh/.config/.zshrc"
alias ezsh="vim $DOTFILES/.zshrc"
alias dotFileInstall="$DOTFILES/install_ubuntu"
alias f5="dotFileInstall && source ~/.zshrc"

