#!/usr/bin/env bash

cheat() {
  curl https://cheat.sh/"$1"
}

addToPath() {
    if [[ "$PATH" != *"$1"* ]]; then
        export PATH=$PATH:$1
    fi
}

addToPathFront() {
    if [[ "$PATH" != *"$1"* ]]; then
        export PATH=$1:$PATH
    fi
}

useSSH() {
    if [ -z "$SSH_AGENT_PID" ] || ! ps -p $SSH_AGENT_PID 2>/dev/null; then
        echo "No SSH Agent found"

        AGENT_INFO=$(ps -ef | grep "ssh-agent" | grep -v "grep" | head -n 1)
        if [ -n "$AGENT_INFO" ]; then
            AGENT_PID=$(echo $AGENT_INFO | awk '{print $2}')
            SOCKET=$(ls -l /tmp/ssh-*/agent.* | grep $((AGENT_PID -1)) | awk '{print $9}')
            export SSH_AGENT_PID=$AGENT_PID
            export SSH_AUTH_SOCK=$SOCKET
            echo "Connected to an existing ssh-agent: PID=$SSH_AGENT_PID, Socket=$SSH_AUTH_SOCK"
        else
            echo "Starting new SSH Agent"
            eval $(ssh-agent -s)
        fi
    fi

    ssh-add -l &>/dev/null
    if [ $? != 0 ]; then
        echo "Adding keys"
        ssh-add
    else
        echo "All good"
    fi
}
